[build]
  publish = "."
  command = "echo 'No build step needed'"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "none"
